name: Upload TestFlight

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [macos-14]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer'
      
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Cache
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
       
    - name: Upload a new build to App Store Connect
      env:
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      run: bundle exec fastlane beta